### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by kyle1106** [kyle1106/935-32-jailbreak#3]
its a compilation of all diffrent unfinished jailbreaks will someone extract the ipa and remove bugs

**Comment by iBootBeta2** [comment]
I can surely help if you need it.

**Comment by kyle1106** [comment]
Thank you extract the ipa have a look if u can see what's causing it to crash

**Comment by iBootBeta2** [comment]
Okay, I'll do so in a few minutes if that's okay. Any contactable email I can communicate with you?

**Comment by kyle1106** [comment]
Kyled1106@gmail.com

**Comment by kyle1106** [comment]
Email me so I can save ur address

**Comment by iBootBeta2** [comment]
Okay, will do now.

**Comment by iBootBeta2** [comment]
Or am I able to iMessage?
